default:
    suites:
        default:
            paths: [%paths.base%/../../src/PHPBDD/PosterBundle/Tests/Features]
            type: symfony_bundle
            bundle: PHPBDDPosterBundle
            mink_session: selenium2
            contexts:
                - PHPBDD\PosterBundle\Tests\Features\Context\FeatureContext
    extensions:
        Behat\Symfony2Extension: ~
        Behat\MinkExtension:
            files_path: %paths.base%/../../web/images
            base_url: http://phpbdd.test:8000/
            sessions:
                default:
                    symfony2: ~
                goutte:
                    goutte: ~
                selenium2:
                    selenium2: ~