version: '2'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - '3306:3306'
  base:
    build: ./base
    ports:
      - '8000:80'
    depends_on:
      - mysql
    extra_hosts:
      - phpbdd.test:127.0.0.1
    entrypoint: /root/wait-for-it.sh 0.0.0.0:3306 --
volumes:
  db:
